---
- hosts: all
  become: yes
  tasks: 
  - name: install apache2
    apt:
      name: apache2
      state: present
  - name: edit text in apache2
    template:
      src: index.j2
      dest: var/www/html/index.html
       