---
- hosts: all
  become: yes
  tasks:
  - name: install wget
    apt:
      name: wget
      stateee: present
  - name: install git
    apt: 
      name: git
      state: present
  - name: install tree
    apt: 
      name: tree
      state: present