---
- hosts: all 
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: Start httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"