---
- hosts: 172.31.1.106
  become: yes
  tasks:
  - name: install tree software
    apt:
     name: tree
     state: present
  - name: install apache2 software
    apt:
     name: wget
     state: present
