---
- hosts: all
  become: yes
  vars:
   myvar1: tree
   myvar2: git
   myvar3: wget
  tasks:
  - name: I want to show message of tree
    debug:
      msg: "{{myvar1}}"
  - name: I want to show message of git
    debug:
      msg: "{{myvar2}}"
  - name: I want to show message of wget
    debug:
      msg: "{{myvar3}}"
    